# Generated by Django 5.2.12 on 2026-03-25 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Gym',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('district', models.CharField(max_length=120)),
                ('region', models.CharField(blank=True, default='Toshkent viloyati', max_length=120)),
                ('address', models.CharField(blank=True, default='', max_length=255)),
                ('phone', models.CharField(blank=True, default='', max_length=40)),
                ('rating', models.FloatField(default=0)),
                ('reviews_count', models.IntegerField(default=0)),
                ('description', models.TextField(blank=True, default='')),
                ('monthly_price', models.IntegerField(default=0)),
                ('entry_price', models.IntegerField(default=0)),
                ('hours', models.CharField(blank=True, default='', max_length=80)),
                ('is_open', models.BooleanField(default=True)),
                ('facilities', models.JSONField(blank=True, default=list)),
                ('sports', models.JSONField(blank=True, default=list)),
                ('gradient', models.CharField(blank=True, default='', max_length=255)),
                ('accent_color', models.CharField(blank=True, default='#0078FF', max_length=80)),
                ('lat', models.FloatField(default=0)),
                ('lng', models.FloatField(default=0)),
            ],
            options={
                'ordering': ['-rating'],
            },
        ),
    ]
