from django.core.management.base import BaseCommand

from gyms.models import Gym


class Command(BaseCommand):
    help = 'Seed initial gym data (dev)'

    def handle(self, *args, **options):
        gyms = [
            {
                'id': 1,
                'name': 'Titan Sport Club',
                'district': 'Chilonzor tumani',
                'region': 'Toshkent viloyati',
                'address': "Chilonzor ko'chasi, 14-uy, Toshkent",
                'phone': '+998901234567',
                'rating': 4.9,
                'reviews_count': 214,
                'description': "Titan Sport Club — zamonaviy trenajorlar, professional murabbiylar va qulay muhitga ega Toshkentning eng yirik sport markazlaridan biri. Har bir a'zo uchun individual yondashuv ta'minlanadi.",
                'monthly_price': 450000,
                'entry_price': 25000,
                'hours': '07:00 — 23:00',
                'is_open': True,
                'facilities': ['shower', 'parking', 'wifi', 'locker', 'ac', 'cardio', 'strength', 'sauna'],
                'sports': ['gym', 'running'],
                'gradient': 'linear-gradient(135deg, #0057b3 0%, #0078FF 60%, #3399ff 100%)',
                'accent_color': '#0078FF',
                'lat': 41.2891,
                'lng': 69.2156,
            },
            {
                'id': 2,
                'name': 'Muscle Factory',
                'district': 'Yunusobod tumani',
                'region': 'Toshkent viloyati',
                'address': "Amir Temur shoh ko'chasi, 108B, Toshkent",
                'phone': '+998901234568',
                'rating': 4.7,
                'reviews_count': 178,
                'description': "Muscle Factory professional bodybuilding va powerlifting uchun maxsus jihozlangan sport zali. Tajribali murabbiylar bilan birgalikda maqsadingizga erishish yanada oson.",
                'monthly_price': 380000,
                'entry_price': 20000,
                'hours': '06:00 — 22:00',
                'is_open': True,
                'facilities': ['shower', 'locker', 'ac', 'cardio', 'strength', 'cafe'],
                'sports': ['weightlifting', 'gym'],
                'gradient': 'linear-gradient(135deg, #0a0f1e 0%, #0d1b3e 60%, #1a3a6e 100%)',
                'accent_color': '#1a56db',
                'lat': 41.3352,
                'lng': 69.2967,
            },
            {
                'id': 3,
                'name': 'FitLife Center',
                'district': "Mirzo Ulug'bek tumani",
                'region': 'Toshkent viloyati',
                'address': "Mirzo Ulug'bek ko'chasi, 55, Toshkent",
                'phone': '+998901234569',
                'rating': 4.8,
                'reviews_count': 302,
                'description': "FitLife Center barcha yoshlar uchun mos, qulay va keng maydonga ega zamonaviy fitness markazi. Yoga, kardio, kuch mashqlari va guruh darslari bir joyda.",
                'monthly_price': 320000,
                'entry_price': 18000,
                'hours': '07:00 — 22:00',
                'is_open': True,
                'facilities': ['shower', 'parking', 'wifi', 'locker', 'ac', 'cardio', 'strength', 'pool'],
                'sports': ['yoga', 'gym', 'running'],
                'gradient': 'linear-gradient(135deg, #6fcf00 0%, #96E20C 60%, #b4f53a 100%)',
                'accent_color': '#5aa800',
                'lat': 41.3105,
                'lng': 69.3198,
            },
            {
                'id': 4,
                'name': 'Power Zone Gym',
                'district': 'Shayxontohur tumani',
                'region': 'Toshkent viloyati',
                'address': "Navoi ko'chasi, 30, Toshkent",
                'phone': '+998901234570',
                'rating': 4.6,
                'reviews_count': 145,
                'description': "Power Zone — kuchli mashqlar va intensiv trenirovkalar uchun mo'ljallangan sport zali. Olimpik shtangalar va zamonaviy mashina jihozlari bilan to'liq jihozlangan.",
                'monthly_price': 290000,
                'entry_price': 15000,
                'hours': '08:00 — 22:00',
                'is_open': True,
                'facilities': ['shower', 'locker', 'ac', 'strength', 'cardio'],
                'sports': ['weightlifting', 'gym', 'running'],
                'gradient': 'linear-gradient(135deg, #00b4d8 0%, #0096c7 60%, #0077b6 100%)',
                'accent_color': '#0096c7',
                'lat': 41.3148,
                'lng': 69.2312,
            },
            {
                'id': 5,
                'name': 'Champion Fitness',
                'district': 'Olmazor tumani',
                'region': 'Toshkent viloyati',
                'address': "Olmazar ko'chasi, 7, Toshkent",
                'phone': '+998901234571',
                'rating': 4.5,
                'reviews_count': 98,
                'description': "Champion Fitness — arzon narxda sifatli xizmat taqdim etadigan sport zali. Yoshlar va talabalar uchun maxsus chegirmalar mavjud.",
                'monthly_price': 250000,
                'entry_price': 12000,
                'hours': '07:00 — 21:00',
                'is_open': False,
                'facilities': ['shower', 'locker', 'cardio', 'strength', 'wifi'],
                'sports': ['gym', 'weightlifting'],
                'gradient': 'linear-gradient(135deg, #7c3aed 0%, #6d28d9 60%, #5b21b6 100%)',
                'accent_color': '#7c3aed',
                'lat': 41.3267,
                'lng': 69.2089,
            },
            {
                'id': 6,
                'name': 'Elite Sport Palace',
                'district': 'Yakkasaroy tumani',
                'region': 'Toshkent viloyati',
                'address': "Istiqbol ko'chasi, 21, Toshkent",
                'phone': '+998901234572',
                'rating': 4.9,
                'reviews_count': 421,
                'description': "Elite Sport Palace — 5 qavat va 3000 m² maydoniga ega, premium darajadagi sport va dam olish markazi. Aqua zona, SPA, sauna va to'liq professional trenajorlar.",
                'monthly_price': 650000,
                'entry_price': 35000,
                'hours': '06:00 — 00:00',
                'is_open': True,
                'facilities': ['shower', 'parking', 'wifi', 'locker', 'ac', 'cardio', 'strength', 'sauna', 'pool', 'cafe'],
                'sports': ['gym', 'swimming', 'weightlifting'],
                'gradient': 'linear-gradient(135deg, #b45309 0%, #d97706 60%, #f59e0b 100%)',
                'accent_color': '#d97706',
                'lat': 41.2850,
                'lng': 69.2590,
            },
            {
                'id': 7,
                'name': 'Body Art Fitness',
                'district': 'Uchtepa tumani',
                'region': 'Toshkent viloyati',
                'address': "Uchtepa ko'chasi, 45, Toshkent",
                'phone': '+998901234573',
                'rating': 4.4,
                'reviews_count': 73,
                'description': "Body Art Fitness — ayollar va erkaklar uchun alohida seksiyalarga ega, qulay va xavfsiz sport muhiti. Zumba, aerobika va pilates darslari kundalik jadvalda.",
                'monthly_price': 300000,
                'entry_price': 16000,
                'hours': '08:00 — 21:00',
                'is_open': True,
                'facilities': ['shower', 'locker', 'ac', 'cardio', 'wifi'],
                'sports': ['yoga', 'gym', 'running'],
                'gradient': 'linear-gradient(135deg, #be185d 0%, #db2777 60%, #ec4899 100%)',
                'accent_color': '#db2777',
                'lat': 41.2742,
                'lng': 69.2015,
            },
            {
                'id': 8,
                'name': 'Pro Fitness Club',
                'district': 'Bektemir tumani',
                'region': 'Toshkent viloyati',
                'address': "Bektemir ko'chasi, 3, Toshkent",
                'phone': '+998901234574',
                'rating': 4.6,
                'reviews_count': 112,
                'description': "Pro Fitness Club — qulay joylashgan, 24/7 rejimida ishlaydigan, raqamli monitoring tizimiga ega zamonaviy sport zali.",
                'monthly_price': 350000,
                'entry_price': 18000,
                'hours': '24/7',
                'is_open': True,
                'facilities': ['shower', 'parking', 'wifi', 'locker', 'ac', 'cardio', 'strength'],
                'sports': ['gym', 'running', 'weightlifting'],
                'gradient': 'linear-gradient(135deg, #065f46 0%, #059669 60%, #10b981 100%)',
                'accent_color': '#059669',
                'lat': 41.2718,
                'lng': 69.3445,
            },
            {
                'id': 9,
                'name': 'Humo Sport Complex',
                'district': "Mirobod tumani",
                'region': 'Toshkent viloyati',
                'address': "Mustaqillik ko'chasi, 63, Toshkent",
                'phone': '+998901234575',
                'rating': 4.8,
                'reviews_count': 289,
                'description': "Humo Sport Complex — olimpiya standartidagi jihozlar bilan ta'minlangan, milliy sportchilar va amatörlar uchun ham qulay muhit yaratilgan premium sport markazi.",
                'monthly_price': 550000,
                'entry_price': 30000,
                'hours': '06:00 — 23:00',
                'is_open': True,
                'facilities': ['shower', 'parking', 'wifi', 'locker', 'ac', 'cardio', 'strength', 'sauna', 'pool'],
                'sports': ['swimming', 'gym', 'weightlifting', 'running'],
                'gradient': 'linear-gradient(135deg, #1e3a5f 0%, #1e40af 60%, #3b82f6 100%)',
                'accent_color': '#1e40af',
                'lat': 41.2978,
                'lng': 69.2780,
            },
            {
                'id': 10,
                'name': 'Namangan CrossFit',
                'district': 'Sergeli tumani',
                'region': 'Toshkent viloyati',
                'address': "Sergeli ko'chasi, 18, Toshkent",
                'phone': '+998901234576',
                'rating': 4.7,
                'reviews_count': 156,
                'description': "CrossFit va funksional trenirovkalar uchun maxsus jihozlangan zamonaviy sport markazi. Guruh mashg'ulotlari va individual trening imkoniyatlari mavjud.",
                'monthly_price': 400000,
                'entry_price': 22000,
                'hours': '06:00 — 22:00',
                'is_open': True,
                'facilities': ['shower', 'locker', 'ac', 'cardio', 'strength', 'wifi', 'parking'],
                'sports': ['weightlifting', 'gym', 'running'],
                'gradient': 'linear-gradient(135deg, #7f1d1d 0%, #dc2626 60%, #ef4444 100%)',
                'accent_color': '#dc2626',
                'lat': 41.2480,
                'lng': 69.2650,
            },
        ]

        for g in gyms:
            Gym.objects.update_or_create(
                id=g['id'],
                defaults={k: v for k, v in g.items() if k != 'id'},
            )

        self.stdout.write(self.style.SUCCESS('Seeded gyms.'))

